---
- name: update netbox django
  django_manage:
    command: "{{ item }}"
    app_path: "{{ netbox_install_directory }}/netbox/netbox"
    virtualenv: "{{ netbox_install_directory }}/netbox"
  listen: "update netbox"
  with_items:
    - migrate 
    - collectstatic

- name: restart supervisor
  service:
    name: supervisor
    state: restarted
  listen: "restart supervisor"

- name: restart netbox
  supervisorctl:
    name: netbox 
    state: restarted
